# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-f457786d-8159-4c9c-8e54-4aed394e6c24";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-f457786d-8159-4c9c-8e54-4aed394e6c24".device =
    "/dev/disk/by-uuid/f457786d-8159-4c9c-8e54-4aed394e6c24";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/DED3-4E1E";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/home/arno/games" = {
    device = "/dev/disk/by-uuid/c81c7f3e-5d68-46f6-9f1f-b4e001f663a3";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/5a756235-4820-4a9c-bc9a-48c6860df52e"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
