import = ["/home/arno/.config/alacritty/themes/themes/carbonfox.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.96

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[font]
size=10
